version: '2'
services:
    inzynierka-app:
        image: inzynierka
        external_links:
            - inzynierka-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/inzynierka?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    inzynierka-mysql:
        extends:
            file: mysql.yml
            service: inzynierka-mysql
